# Generated by Django 5.2.18 on 2026-10-08 16:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_installment_reminders"),
        ("projects", "0003_client_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("active", models.BooleanField(default=True)),
                ("position", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["position", "name"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="bill_to_address",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="invoice",
            name="issue_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name="invoice",
            name="prefix",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax_name",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="quotation",
            name="bill_to_address",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="quotation",
            name="issue_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name="quotation",
            name="prefix",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="quotation",
            name="proposal_text",
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name="quotation",
            name="tax_name",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="quotation",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="counter",
            name="kind",
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="number",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="number",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Delivered"),
                    ("accepted", "Accepted"),
                    ("rejected", "Lost"),
                    ("dead", "Dead"),
                    ("expired", "Expired"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="RecurringInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("prefix", models.CharField(default="INV", max_length=8)),
                (
                    "currency",
                    models.CharField(
                        choices=[("BDT", "BDT (৳)"), ("USD", "USD ($)")],
                        default="BDT",
                        max_length=3,
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("tax_name", models.CharField(blank=True, max_length=40)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("notes", models.TextField(blank=True, max_length=2000)),
                ("bill_to_address", models.TextField(blank=True, max_length=500)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Every 3 months"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("next_run", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("due_days", models.PositiveIntegerField(default=15)),
                ("auto_issue", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("ended", "Ended"),
                        ],
                        default="active",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecurringItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=300)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "recurring",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="billing.recurringinvoice",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="RecurringRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_date", models.DateField()),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_run",
                        to="billing.invoice",
                    ),
                ),
                (
                    "recurring",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="billing.recurringinvoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-run_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("recurring", "run_date"), name="uniq_recurring_run"
                    )
                ],
            },
        ),
    ]
