# Generated by Django 5.2.18 on 2026-10-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_tax_prefix_recurring"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="revision",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="invoice",
            name="subtitle",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="counted",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="details",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="note",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="risk",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not stated"),
                    ("low", "Low"),
                    ("mid", "Medium"),
                    ("high", "High"),
                ],
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="time_estimate",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="unit_price_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="work_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not stated"),
                    ("new", "To do"),
                    ("partial", "Partly done"),
                    ("done", "Done"),
                ],
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="payment_plan",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="quotation",
            name="revision",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="quotation",
            name="risks",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="quotation",
            name="sections",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="quotation",
            name="subtitle",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="counted",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="details",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="note",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="risk",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not stated"),
                    ("low", "Low"),
                    ("mid", "Medium"),
                    ("high", "High"),
                ],
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="time_estimate",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="unit_price_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="work_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not stated"),
                    ("new", "To do"),
                    ("partial", "Partly done"),
                    ("done", "Done"),
                ],
                max_length=7,
            ),
        ),
    ]
