# Generated by Django 5.2.18 on 2026-10-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
    ]
