# Generated by Django 5.2.18 on 2026-10-07 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0002_document_project"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spent_on", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hosting", "Hosting and servers"),
                            ("domain", "Domains"),
                            ("software", "Software and tools"),
                            ("contractor", "Contractors"),
                            ("marketing", "Marketing"),
                            ("transport", "Transport"),
                            ("fees", "Platform and bank fees"),
                            ("tax", "Tax and licences"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=12,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "currency",
                    models.CharField(
                        choices=[("BDT", "BDT (৳)"), ("USD", "USD ($)")],
                        default="BDT",
                        max_length=3,
                    ),
                ),
                ("vendor", models.CharField(blank=True, max_length=150)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="projects.project",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.document",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-spent_on", "-id"],
            },
        ),
    ]
