# Generated by Django 5.2.18 on 2026-10-08 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_on", models.DateField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("upwork", "Upwork"),
                            ("fiverr", "Fiverr"),
                            ("freelancer", "Freelancer.com"),
                            ("direct", "Direct client (outside the app)"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=12,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=300)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "currency",
                    models.CharField(
                        choices=[("BDT", "BDT (৳)"), ("USD", "USD ($)")],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-earned_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("settled_on", models.DateField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("upwork", "Upwork"),
                            ("fiverr", "Fiverr"),
                            ("payoneer", "Payoneer"),
                            ("wise", "Wise"),
                            ("paypal", "PayPal"),
                            ("bank", "Bank transfer"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("earned_usd", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "marketplace_fee_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "transfer_fee_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "reference_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("received_bdt", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "bank_charge_bdt",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "vat_bdt",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tax_withheld_bdt",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "other_charge_bdt",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-settled_on", "-id"],
            },
        ),
    ]
