import uuid

from django.conf import settings
from django.db import models


class Document(models.Model):
    """A private file (contract, quotation, invoice copy). Bytes live in storage, not the DB."""

    class Category(models.TextChoices):
        MOU = "mou", "MOU"
        TOR = "tor", "Terms of reference (TOR)"
        AGREEMENT = "agreement", "Agreement"
        QUOTATION = "quotation", "Quotation"
        INVOICE = "invoice", "Invoice"
        RECEIPT = "receipt", "Receipt"
        OTHER = "other", "Other"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=200)
    category = models.CharField(max_length=16, choices=Category.choices, default=Category.OTHER)
    # The client this document belongs to; they can see it only once `shared_with_client` is on.
    client = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.PROTECT,
        related_name="documents",
    )
    project = models.ForeignKey(
        "projects.Project",
        null=True,
        blank=True,
        on_delete=models.PROTECT,
        related_name="documents",
    )
    shared_with_client = models.BooleanField(default=False)
    uploaded_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL, related_name="+"
    )
    # Storage key is generated by us (never the user's filename), so it cannot collide or traverse.
    file_key = models.CharField(max_length=200, unique=True, editable=False)
    original_name = models.CharField(max_length=255)
    content_type = models.CharField(max_length=100)
    size = models.PositiveIntegerField()
    sha256 = models.CharField(max_length=64)
    created_at = models.DateTimeField(auto_now_add=True)
    deleted_at = models.DateTimeField(null=True, blank=True)  # soft delete; the file is kept

    class Meta:
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return self.title
