# Generated by Django 5.2.18 on 2026-10-06 20:27

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                (
                    "need",
                    models.CharField(
                        choices=[
                            ("ecommerce", "Online store (eCommerce)"),
                            ("business_app", "Business management app"),
                            ("admin_dashboard", "Admin dashboard"),
                            ("backend_api", "Backend API or integration"),
                            ("improve_existing", "Improve an existing app"),
                            ("other", "Something else"),
                        ],
                        max_length=32,
                    ),
                ),
                ("details", models.TextField(max_length=5000)),
                (
                    "budget",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unsure", "Not sure yet"),
                            ("under_500", "Under $500"),
                            ("500_1500", "$500 - $1,500"),
                            ("1500_5000", "$1,500 - $5,000"),
                            ("over_5000", "$5,000+"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "timeline",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("flexible", "Flexible"),
                            ("within_1m", "Within 1 month"),
                            ("1_3m", "1 - 3 months"),
                            ("over_3m", "3+ months"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("read", "Read"),
                            ("replied", "Replied"),
                            ("archived", "Archived"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("notify_error", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
